# Generated by Django 4.1.4 on 2023-01-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0003_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members_2',
            field=models.CharField(choices=[], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
