# Generated by Django 4.1.4 on 2023-01-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0004_group_members_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members_2',
        ),
    ]
