# Generated by Django 4.1.4 on 2023-02-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
    ]
