# Generated by Django 4.1.4 on 2023-02-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0002_timedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedate',
            name='time_now',
            field=models.DateField(auto_now=True),
        ),
    ]
