# Generated by Django 4.1.4 on 2023-02-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0003_timedate_time_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedate',
            name='time_now',
            field=models.DateField(),
        ),
    ]
